export const ERROR_CODES = {
  // Server
  SERVER_ERROR: "SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  ACCESS_DENIED: "ACCESS_DENIED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",

  // Auth
  BASE_AUTH_TOKEN_REQUIRED: "BASE_AUTH_TOKEN_REQUIRED",
  BASE_INVALID_ACCESS_TOKEN: "BASE_INVALID_ACCESS_TOKEN",
  BASE_TOKEN_EXPIRED: "BASE_TOKEN_EXPIRED",
  AUTH_USER_NOT_EXIST: "AUTH_USER_NOT_EXIST",

  // Profile
  PROFILE_NOTFOUND: "PROFILE_NOTFOUND",

  // Bars / S3
  BARS_INVALID_FILE_TYPE: "BARS_INVALID_FILE_TYPE",
  BARS_INVALID_INPUT: "BARS_INVALID_INPUT",
  BARS_FILE_NOT_FOUND: "BARS_FILE_NOT_FOUND",
  BARS_ACCESS_DENIED: "BARS_ACCESS_DENIED",

  // Subscription
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
} as const;
